/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMeetupsRouteImport } from './routes/_app.meetups'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppMeetupsCreateRouteImport } from './routes/_app.meetups.create'
import { Route as AppMeetupsIdRouteImport } from './routes/_app.meetups.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMeetupsRoute = AppMeetupsRouteImport.update({
  id: '/meetups',
  path: '/meetups',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetupsCreateRoute = AppMeetupsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppMeetupsRoute,
} as any)
const AppMeetupsIdRoute = AppMeetupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMeetupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/meetups': typeof AppMeetupsRouteWithChildren
  '/meetups/$id': typeof AppMeetupsIdRoute
  '/meetups/create': typeof AppMeetupsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/meetups': typeof AppMeetupsRouteWithChildren
  '/meetups/$id': typeof AppMeetupsIdRoute
  '/meetups/create': typeof AppMeetupsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/meetups': typeof AppMeetupsRouteWithChildren
  '/_app/meetups/$id': typeof AppMeetupsIdRoute
  '/_app/meetups/create': typeof AppMeetupsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/meetups'
    | '/meetups/$id'
    | '/meetups/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/meetups'
    | '/meetups/$id'
    | '/meetups/create'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/meetups'
    | '/_app/meetups/$id'
    | '/_app/meetups/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/meetups': {
      id: '/_app/meetups'
      path: '/meetups'
      fullPath: '/meetups'
      preLoaderRoute: typeof AppMeetupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetups/create': {
      id: '/_app/meetups/create'
      path: '/create'
      fullPath: '/meetups/create'
      preLoaderRoute: typeof AppMeetupsCreateRouteImport
      parentRoute: typeof AppMeetupsRoute
    }
    '/_app/meetups/$id': {
      id: '/_app/meetups/$id'
      path: '/$id'
      fullPath: '/meetups/$id'
      preLoaderRoute: typeof AppMeetupsIdRouteImport
      parentRoute: typeof AppMeetupsRoute
    }
  }
}

interface AppMeetupsRouteChildren {
  AppMeetupsIdRoute: typeof AppMeetupsIdRoute
  AppMeetupsCreateRoute: typeof AppMeetupsCreateRoute
}

const AppMeetupsRouteChildren: AppMeetupsRouteChildren = {
  AppMeetupsIdRoute: AppMeetupsIdRoute,
  AppMeetupsCreateRoute: AppMeetupsCreateRoute,
}

const AppMeetupsRouteWithChildren = AppMeetupsRoute._addFileChildren(
  AppMeetupsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppMeetupsRoute: typeof AppMeetupsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppMeetupsRoute: AppMeetupsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
